### ISSUE TITLE
Peer to Peer Code Review: Module 2 & Week 1

### ISSUE THREAD

**Issue by DebbyMiressa** [kal2944/capstone-project1#3]
Hi @kal2944 👋 

Your work is very well done! Especially, the animation and translation choices were excellent. But here are a few issues I noticed that might need a fix.
1) The images are not displayed on the live demo. You can fix it by correcting the path for image source.
2) The font used has a small size. Enlarge the texts to make your content visible and interesting to read.
3) The images as well as the cards should not overlap with the header/navbar when the element is hovered on.

Cheers 🥂

**Comment by kal2944** [comment]
well noted! thank you.
